In [ ]:
import pandas as pd

# ROOT
root_path = "C:/Users/jackm/Documents/GitHub/ms-capstone-TTS-natlang-styleprompts"

# StyleTalk

In [ ]:
df_styletalk_eval_meta = pd.read_csv(
    f"{root_path}/src/data/raw/styletalk/annotations/eval.csv",
    sep=",",            # delimiter
    encoding="utf-8",   # or "latin1"
    na_values=["NA", ""],
)

df_styletalk_eval_meta

,diag_id,context,curr_audio_id,res_audio_id,curr_text,res_text,curr_emotion,curr_speed,curr_volume,res_emotion,res_speed,res_volume
0,health_306,"A : I've been trying to eat healthier lately, ...",health_306/c_0.wav,health_306/r_0.wav,B: Sometimes it's hard to stick to those habit...,"Yeah, it can be a real challenge when life g...",unfriendly,fast,loud,unfriendly,normal,normal
1,health_306,"A : I've been trying to eat healthier lately, ...",health_306/c_2.wav,health_306/r_2.wav,B: Sometimes it's hard to stick to those habit...,"True, I'm hoping I can make these changes a ...",friendly,normal,normal,cheerful,normal,normal
2,music_478,"A : Oh, have you heard the new album by The We...",music_478/c_0.wav,music_478/r_0.wav,"B: Hmm, I might go to their concert next month.","Oh, that could be fun. If you're going, mayb...",neutral,normal,normal,neutral,normal,normal
3,movie_430,"A : Seriously, that last movie we saw was just...",movie_430/c_1.wav,movie_430/r_1.wav,B: I just hope the next one we pick doesn't en...,"Whoa, take it easy! We'll make sure it's a h...",unfriendly,fast,loud,unfriendly,normal,normal
4,movie_48,A : Did you see the latest superhero movie? It...,movie_48/c_2.wav,movie_48/r_2.wav,"B: I just prefer movies with more depth, you k...","Absolutely, there's plenty of films with dep...",friendly,normal,loud,cheerful,normal,normal
...,...,...,...,...,...,...,...,...,...,...,...,...
853,game_408,"A : I can't believe we aced that level, that w...",game_408/c_0.wav,game_408/r_0.wav,"B: Sure, just give me a second to set things u...","No worries, take your time, we're not in a r...",neutral,slow,quiet,friendly,normal,normal
854,food_233,A : I can't believe how amazing that new Thai ...,food_233/c_0.wav,food_233/r_0.wav,B: They did seem to have a lot of options on t...,"Exactly! There's so much to try, maybe anoth...",neutral,normal,normal,cheerful,normal,normal
855,music_21,"A : I just found this amazing new band, and th...",music_21/c_2.wav,music_21/r_2.wav,B: I think I've heard about them once before.,That's cool! They've been gaining popularity...,friendly,normal,normal,cheerful,normal,normal
856,music_21,"A : I just found this amazing new band, and th...",music_21/c_1.wav,music_21/r_1.wav,B: I think I've heard about them once before.,"Wait, why do you sound mad? Did you not like...",unfriendly,fast,loud,unfriendly,normal,loud
857,music_21,"A : I just found this amazing new band, and th...",music_21/c_0.wav,music_21/r_0.wav,B: I think I've heard about them once before.,"Oh, really? They've only recently started ge...",neutral,slow,quiet,neutral,slow,normal

# LibriTTS-P

In [ ]:


df_metadatatags = pd.read_csv(
    f"{root_path}/src/data/raw/libritts/libritts-p/data/metadata_w_style_prompt_tags_v230922.csv",
    sep=",",            # delimiter
    encoding="utf-8",   # or "latin1"
    na_values=["NA", ""],
)

df_metadatatags

In [ ]:
df_prompt_cands = pd.read_csv(
    f"{root_path}/src/data/raw/libritts/libritts-p/data/style_prompt_candidates_v230922.csv",
    sep="|", 
    header=None
    , names=["style_prompt_key", "prompts"]
)

# split prompts to list
df_prompt_cands["prompts"] = df_prompt_cands["prompts"].str.split(";")

# explode for one propmt per row
df_prompt_cands = df_prompt_cands.assign(prompt=df_prompt_cands["prompts"]).explode("prompt")
df_prompt_cands["prompt"] = df_prompt_cands["prompt"].str.strip()
df_prompt_cands = df_prompt_cands.drop(columns="prompts")

df_prompt_cands

          style_prompt_key                                             prompt
0     M_p-low_s-slow_e-low  Ask a low-pitched man to speak slowly with low...
0     M_p-low_s-slow_e-low  Ask a man to speak slowly with low volume and ...
0     M_p-low_s-slow_e-low  Ask a man to speak slowly, his pitch and volum...
0     M_p-low_s-slow_e-low  Ask a man with a low pitch to speak slowly, hi...
0     M_p-low_s-slow_e-low  Command a man with a high-pitched voice to spe...
..                     ...                                                ...
53  F_p-high_s-fast_e-high  Let a woman speak with high pitch, fast speaki...
53  F_p-high_s-fast_e-high  ask a high-pitched woman to speak fast with hi...
53  F_p-high_s-fast_e-high  ask a high-pitched woman to speak quckly with ...
53  F_p-high_s-fast_e-high  ask a woman with a loud voice to say quickly, ...
53  F_p-high_s-fast_e-high  let a high-pitched female person talk in fast ...

[1347 rows x 2 columns]

In [ ]:
# merge datasets, giving one prompt per audio file

merged = df_metadatatags.merge(
    df_prompt_cands,
    on="style_prompt_key",
    how="inner"
)
merged